src/Clients/Web/EnixerPos.Web/Controllers/ManagementController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace EnixerPos.Web.Controllers
{
    public class ManagementController : Controller
    {
        public IActionResult Index()
        {
            try
            {
                string token = HttpContext.Session.GetString("Email");
                if (String.IsNullOrEmpty(token))
                {
                    return RedirectToAction("Index", "Register");
                }
                return View();
            }
            catch(Exception e)
            {
                Console.WriteLine("Error : " + e.Message);
                return RedirectToAction("Index", "Register");
            }
        }

        public IActionResult SuccessPage(string message)
        {
            ViewBag.Message = message;
            return View();
        }

        public IActionResult Error(string message)
        {
            ViewBag.Message = message;
            return View();
        }
    }
}

src/Clients/Web/EnixerPos.Web/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using EnixerPos.Api.ViewModels.Product;
using EnixerPos.Domain.Interfaces;
using EnixerPos.Web.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace EnixerPos.Web.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductService _productService;
        private readonly IMapper _mapper;
        public ProductController(IProductService productService, IMapper mapper)
        {
            _productService = productService;
            _mapper = mapper;
        }

        public IActionResult Index()
        {
            string email = HttpContext.Session.GetString("Email");
            if (String.IsNullOrEmpty(email))
            {
                return RedirectToAction("Index", "Register");
            }
            return View();
        }

        public IActionResult EditItem()
        {
            string email = HttpContext.Session.GetString("Email");
            if (String.IsNullOrEmpty(email))
            {
                return RedirectToAction("Index", "Register");
            }
            ViewBag.Email = email;
            List<ItemModel> items = _productService.GetItems(email).Items;
            List<ItemWebModel> itemWebs = items.Select(x => new ItemWebModel()
            {
                Name = x.Name,
                CategoryName = x.CategoryName,
                Color = x.Color,
                Price = x.Price,
                Cost = x.Cost,
                Option1 = x.Option1,
                Option1Price = x.Option1Price,
                Option2 = x.Option2,
                Option2Price = x.Option2Price,
                Option3 = x.Option3,
                Option3Price = x.Option3Price,
                Option4 = x.Option4,
                Option4Price = x.Option4Price,
                Option5 = x.Option5,
                Option5Price = x.Option5Price,
                Option6 = x.Option6,
                Option6Price = x.Option6Price
            }).ToList();
            ViewData["Items"] = itemWebs;
            return View();
        }

        public IActionResult EditCategory()
        {
            string email = HttpContext.Session.GetString("Email");
            if (String.IsNullOrEmpty(email))
            {
                return RedirectToAction("Index", "Register");
            }
            ViewBag.Email = email;
            List<CategoryModel> categories = _productService.GetCategories(email).Categories;
            List<CategoriesWebModel> categoriesWebs = categories.Select(x => new CategoriesWebModel()
            {
                Name = x.Name,
                Color = x.Color,
                StoreId = x.StoreId,
                CountItem = x.CountItem
            }).ToList();
            ViewData["Categories"] = categoriesWebs;
            return View();
        }

        public IActionResult EditDiscount()
        {
            string email = HttpContext.Session.GetString("Email");
            if (String.IsNullOrEmpty(email))
            {
                return RedirectToAction("Index", "Register");
            }
            ViewBag.Email = email;
            List<DiscountModel> discounts = _productService.GetDiscounts(email).Discounts;
            List<DiscountWebModel> discountWebs = discounts.Select(x => new DiscountWebModel()
            {
                DiscountName = x.DiscountName,
                Amount = x.Amount,
                IsPercentage = x.IsPercentage,
                StoreId = x.StoreId
            }).ToList();
            ViewData["Discounts"] = discountWebs;
            return View();
        }
    }
}

src/Clients/Web/EnixerPos.Web/Views/Product/EditItem.cshtml
@{
    ViewData["Title"] = "EditItem";
}

<h1 class="text-center ">Edit Item</h1>
<section class="content">
    <div class="row">
        <div class="col-sm-12">


            <div class="box">
                <div class="box-header">
                    <h3 class="box-title">Staff</h3>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <table id="example1" class="table table-bordered table-striped text-center">
                        <thead>
                            <tr>
                                <th>Item Name</th>
                                <th>Category</th>
                                <th>Price</th>
                                <th>Cost</th>
                                <th>	</th>
                            </tr>
                        </thead>
                        <tbody id="carTable">
                            @if ((List<ItemWebModel>)ViewData["Items"] == null)
                            {
                                <tr class="odd">
                                    <td valign="top" colspan="10" class="dataTables_empty">No data available in table</td>
                                </tr>
                            }
                            else
                            {
                                foreach (var item in (List<ItemWebModel>)ViewData["Items"])
                                {
                                    <tr>
                                        <td><h3>@item.Name</h3></td>
                                        <td><h3>@item.CategoryName</h3></td>
                                        <td><h3>@item.Price</h3></td>
                                        <td><h3>@item.Cost</h3></td>
                                        <td><button type="button" class="btn-light offset-5 btn-lg">@Html.ActionLink("Delete", "EditItem", "Product")</button></td>
                                    </tr>
                                }
                            }
                        </tbody>
                    </table><br />
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->
</section>
<br />
<br />
<button type="button" class="btn-light offset-5 btn-lg">@Html.ActionLink("Back", "Index", "Product")</button>

src/Clients/Web/EnixerPos.Web/Views/Product/Index.cshtml
@{
    ViewData["Title"] = "Product";
}

<h1 class="text-center ">Management Product</h1>
<button type="button" class="btn-light offset-5 btn-lg">@Html.ActionLink("Edit Item", "EditItem", "Product")</button>
<br />
<br />
<button type="button" class="btn-light offset-5 btn-lg">@Html.ActionLink("Edit Category", "EditCategory", "Product")</button>
<br />
<br />
<button type="button" class="btn-light offset-5 btn-lg">@Html.ActionLink("Edit Discount", "EditDiscount", "Product")</button>
<br />
<br />
<button type="button" class="btn-light offset-5 btn-lg">@Html.ActionLink("Back", "Index", "Management")</button>